const Manager = require("./lib/Manager");
const Engineer = require("./lib/Engineer");
const Intern = require("./lib/Intern");
const inquirer = require("inquirer");
const path = require("path");
const fs = require("fs");

const OUTPUT_DIR = path.resolve(__dirname, "output");
const outputPath = path.join(OUTPUT_DIR, "team.html");

const render = require("./src/page-template.js");


// Gather information about the development team members and render an HTML file
// -----------------------------------------------------------------------------


let teamArray = []                  // array to hold objects generated by user input
let menuOption = ""                 // menu option selected by user


init()
async function init() {

    // Get User Input and Populate teamArray

    // (a) get Manager
    await getUserInput_Manager()

    // repeat until user input complete
    while(menuOption !== "Finish building the team") {

        // process User Selection

            // (b) get Engineer
            if (menuOption === "Add an engineer") {}

            // (c) get Intern
            if (menuOption === "Add an intern") {}


            menuOption = "Finish building the team" // <-- for testing

    }        

    
                

    // Get HTML from teamArray
    const html = render(teamArray)
    //console.log(html)

    // Write HTML to a File
    fs.writeFile(outputPath, html, (err) =>
        err ? console.log(err) : console.log('team.html has been created in the output folder')  
    )

}


// Get User Input
// --------------


// Get "Manager" details from User and append to the Team Array
async function getUserInput_Manager() {

    // array of Questions for user to answer
    const questions = [

        {
            type: 'input',
            name: 'name',
            message: 'What is the NAME of the Manager?',
        },

        {
            type: 'list',
            message: 'What would you like to do next?',
            name: 'menuOption',
            choices: ["Add an engineer", "Add an intern", "Finish building the team"], 
        },

    ]   

    // Ask the user Questions
    await inquirer
        .prompt(questions)

        // With the Answers
        .then((answers) => {

            // Create a New Manager (an instance of the Manager class)
            let manager = new Manager(answers.name, 122, "TEST EMAIL", 88888)

            // Add the New Manager to the Team Array
            teamArray.push(manager)

            // Store the users Menu Selection
            menuOption = answers.menuOption
            console.log(menuOption)
        })

}
